# -*- coding: utf-8 -*-
{
    'name': "Gestion de Parc Informatique",
    'version': '18.0.1.0.0',
    'depends': [
        'base',
        'mail',
        'portal',
        'website',
        'contacts',
        'product',
        'stock',
        'account',
        'helpdesk',
        'rating',
        'auth_signup',
    ],
    'author': "Your Company",
    'category': 'Services/IT',
    'description': """
        Module de gestion de parc informatique avec portail client
    """,
    'data': [
        'security/ir_rule.xml',
        'security/ir.model.access.csv',
        'security/it_security.xml',
        'security/it_park_security.xml',
        'security/it_park_portal_rules.xml',
        'data/partner_category_data.xml',
        'data/it_park_sequences.xml',
        'data/mail_template_data_simple.xml',
        'data/ir_cron_data.xml',
        'data/it_service_type_data.xml',
        'data/init_sql.xml',
        'data/it_ticket_category_data.xml',
        'data/ir_sequence_data.xml',
        'data/it_park_email_templates.xml',
        'views/views.xml',
        'views/templates.xml',
        'views/new_menus.xml',
        'views/res_partner_views.xml',
        'views/it_park_menus.xml',
        'views/menus.xml',
        'views/website_templates.xml',
        'views/website_menus.xml',
        'views/auth_signup_templates.xml',
        'views/it_equipment_views.xml',
        'views/it_software_views.xml',
        'views/it_license_views.xml',
        'views/it_contract_views.xml',
        'views/it_incident_views.xml',
        'views/it_intervention_views.xml',
        'views/it_ticket_views.xml',
        'views/it_dashboard_views.xml',
        'views/it_sla_views.xml',
        'views/it_service_request_views.xml',
        'views/res_company_views.xml',
        'views/res_users_views.xml',
        'views/hr_employee_views.xml',
        'views/helpdesk_views.xml',
        'views/it_park_portal_templates.xml',
        'views/portal_templates.xml',
        'views/portal_ticket_detail.xml',
        'views/portal_ticket_thankyou.xml',
        'views/portal_create_ticket.xml',
        'views/res_config_settings_views.xml',
        'views/it_actions.xml',
        'wizards/assign_equipment_wizard_views.xml',
        'wizards/return_equipment_wizard_views.xml',
        'wizards/it_incident_resolve_wizard_views.xml',
        'wizards/it_ticket_resolve_wizard_views.xml',
        'wizards/it_portal_user_wizard_views.xml',
        'wizards/service_proposal_wizard_views.xml',
        'views/templates/service_request_form.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'it__park/static/src/scss/portal.scss',
            'it__park/static/src/js/portal.js',
            'it__park/static/src/js/portal_enhancements.js',
            'it__park/static/src/js/ticket_notification.js',
            'it__park/static/src/js/website_it_support.js',
            'it__park/static/src/js/signup.js',
        ],
    },
    'demo': [
        'demo/demo.xml',
        'demo/carrefour_demo.xml',
    ],
    'post_init_hook': 'post_init_hook',
    'post_load': 'run_fix_tickets',
    'application': True,
    'installable': True,
    'auto_install': False,
    'icon': '/it__park/static/src/description/park_managment.png',
    'license': 'LGPL-3',
}

